# This is a basic workflow that is manually triggered

name: Test workflow

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  push:
    branches:
    - main
  workflow_dispatch:

jobs:
  # This workflow contains a single job called "greet"
  greet:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Runs a single command using the runners shell
    - name: Checkout repository
      uses: actions/checkout@v2.3.3
      
    - name: Get directories
      run: |
        echo start
        echo "${GITHUB_WORKSPACE}/"
        echo the content of current directory
        ls -a 
       
    - name: Send greeting
      run: echo "Hello ${{ github.event.inputs.name }}"
