# This is a basic workflow that is manually triggered

name: Upload zip workflow in a new release

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  push:
    branches:
      - main
    tags:
      - 'v*.*.*'
  workflow_dispatch:
    # Inputs the workflow accepts.
    inputs:
      name:
        # Friendly description to be shown in the UI instead of 'name'
        description: 'The name of the asset to upload'
        # Input has to be provided for the workflow to run
        required: true
      version:
        description: 'The version of the release'
        required: true

jobs:

  upload:
    # The type of runner that the job will run on
    name: upload a file
    runs-on: ubuntu-latest

  
   
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - uses: actions/checkout@v2

    - name: Get directories
      run: |
        dir=$(find . -mindepth 1 -maxdepth 1 -type d)
        dirs=$(dir)
        echo "DIR=${dirs:10}" >> $GITHUB_ENV
    - name: Set env
      run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
    - uses: meeDamian/github-release@2.0
      with:
        allow_override: true
        token: ${{ secrets.PERSONAL_ACCES_TOKEN }}
        tag:  ${{env.RELEASE_VERSION}}
        name: Initial release
        body: >
          This release is all the labs of TSP labtainers
        gzip: folders
        files: >
          ${{ env.DIR }}
